name: ${pluginName}
version: ${version}
main: ${group}.${packageName}.${pluginName}
api-version: ${paperVersion}
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:${kotlinVersion}
  - org.jetbrains.kotlin:kotlin-reflect:${kotlinVersion}
